insert into genera (id, imageurl, name)
values  (0x220FEEE0BD5A438EB1B282BFFFD92315, 'https://www.llifle.com/photos/Ferocactus_acanthodes_8957_l.jpg', 'Ferocactus'),
        (0x43A8D74F45954B0FA3683E372CE29927, 'https://www.llifle.com/photos/Parodia_arachnitis_17755_l.jpg', 'Parodia'),
        (0x905050A371194C17B4DBCEE7283C5BF6, 'https://llifle.net/thumbnails/Mammillaria_albiflora_8094.jpg', 'Mammillaria'),
        (0x905050A371194C17B4DBCEE7283C5BF7, 'https://www.llifle.com/photos/Frailea_carminifilamentosa_23683_l.jpg', 'Frailea'),
        (0xF5BFA272F06B47A6AF85073E338C3A06, 'https://www.llifle.com/photos/Echinocereus_adustus_14412_l.jpg', 'Echinocereus');

insert into species (id, approved, cold_hardiness, cultivation, description, imageurl, name, added_on, genera_id)
values  (0x0328A79A4E824D079F5AA4E7C707D528, true, 'Reputedly moderately resistant to frost if kept on the dry side prior to, and during, cold weather (hardy to -5 C ° C, for short periods). This cactus needs a period of cool rest in winter to produce flowers abundantly. Without this cool winter period these plants normally won''t get many buds. It may flowers indoors if conditions suit it.', 'Echinocereus cinerascensSN|7775]]SN|7775]] is an easily grown cactus, suited to hanging baskets as well as pots. This cactus is widely cultivated for its flowers, it is among the easiest species to grow, flower and propagate.
Growth rate: It is a relatively rapidly growing and easily flowering species that will make large clumps given the best conditions.
Soils: It likes very porous standard cactus mix soil. Prefer a low pH compost, avoid substrata rich in limestone; otherwise growth will stop altogether.
Repotting: Use pot with good drainage.
Watering: Needs moderate to copious waterings rom March to October, but do not overwater (Rot prone), keep dry in winter.
Fertilization: Feed with a high potassium fertilizer in summer.', 'Echinocereus cinerascensSN|7817]]SN|7775]] is an open, caespitose cactus that produce masses of bright pink or purple blooms up to 12 cm in diameter which finally produce edible and delicious fruits (tastes similar to strawberries just like Echinocereus engelmannii and Echinocereus stramineusSN|7775]]SN|7817]] do). It is quite variable.
Habitat: Growing in patches 6 to 12 dm broad, branching at base, the stems semi-erect, ascending to decumbent about 3 dm tall.
Stems: Soft, pale green (that redden in full sun and with freezing climate), cylindrical, 10-30 cm tall (rarely up to 60 cm), (1,5-)4-10(-12) cm in diameter; erect or slightly prostrate as they age.', 'https://www.llifle.com/photos/Echinocereus_cinerascens_14362_l.jpg', 'Echinocereus cinerascens', '2025-03-21', 0xF5BFA272F06B47A6AF85073E338C3A06),
        (0x1D5F3011754D42B3AB6F6E67C8739CE1, true, '', 'This is an easy plant to cultivate. It likes to be kept cool, and needs only a short rest in winter. It can can tolerate light frost. Grow in full sun or light shade, but it doesn''t like full, hot blazing sun in the central summer months. Water occasionally in winter so the roots do not dry out completely, and water regularly in summer. Some growers suggest to use exclusively rain water. But be careful, as it will rot easily if the substrate is wet and cold. It tends to lose its roots in winter. The root system of this plant is comparatively small, and it is best to grow it in a shallow pot using a neutral to slightly acidic compost, with plenty of extra grit. Give an occasional tonic of sequestrated iron.', 'Parodia buiningiiSN|20510]]SN|20510]] (Buxbaum) N.P. Taylor is a solitary, flattened cactus only a few cm in height with long, straw-yellow spines. It bears large and showy yellow flowers, and produces hairy fruit and black seeds.
Stem: Simple, depressed-spherical to spherical, or oblate, , not woolly apically, grass green, pale grey, bluish to bright emerald green, up to 8 cm tall and 12 cm in diameter.
Ribs: About 16, pronounced, straight and sharp, up to 2 centimetres in height, with narrow blade-like tubercles between the areoles.
Areoles: Sunken under the tubercles, initially woolly, losing the wool as they mature.
Central spines: (3-)4, forming a cross, straight, stiff, yellowish or straw-coloured, dark brown at base 2-3 cm long.
Radial spines: 2-3, very similar to the centrals but smaller.
Flowers: 7 cm long, 8 cm in diameter, shiny, pale yellow with a distinct red-violet stigma. Pericarpel and tube with thick dark to light brown wool.
Blooming season: Summer.
Fruit: Elongating at base, up to 3 cm long.
Seeds: Helmet-shaped to 1.4 mm, finely tuberculate, matt black.', 'https://www.llifle.com/photos/Parodia_buiningii_11766_l.jpg', 'Parodia buiningii', '2025-03-21', 0x43A8D74F45954B0FA3683E372CE29927),
        (0x1DF31433B78548838AFD29DFDD679837, true, 'It is moderately frost resistant if kept dry and hardy to -4° C for short periods (depending on varieties and growing conditions). However warmth throughout the year will increase the grower''s success (at temperatures from 5 to 15 degrees centigrade during rest season).
Exposition: The plant tolerates bright situations which encourages flowering and heavy spine production, but is likely to suffer from sun scorch or stunted growth if over exposed to direct sunlight during the hottest part of the day in summer. It grows well with filtered sunlight or afternoon shade.', 'Parodia werneriSN|19997]]SN|19997]] (syn: Notocactus uebelmannianusSN|19998]]SN|19998]]) is easy to grow and quite resistant to neglect. Nevertheless, it is appropriate to provide adequate growing conditions in order to obtain abundant blooms.
Growth rate: It is a relatively rapidly growing species that will make large clumps given the best conditions.
Soils: It needs a standard cactus mix soil with an excellent drainage. Prefer a low pH compost, avoid substrata too rich in limestone.
Repotting: This plant needs plenty of space for its roots, repotting should be done every other year or when the it has outgrown its pot. It is rot prone and should be planted in a shallow pot. Use pot with good drainage.
Watering: Needs regular water in spring to autumn in summer (it is more demanding than other cactus), but do not overwater, keep dry in winter or give them a very small amount about once a month in winter to prevent shrinkage and root loss.
Fertilization: Feed with a high potassium fertilizer in summer. Regular water in spring to autumn. I tend to', 'Parodia werneriSN|19997]]SN|19997]] is a a nice cactus usually solitary, sometimes branching basally to form small clumps. It has glossy green body with appressed spines and bears a ring of the most amazing magenta to royal purple flowers every spring.
Replaced synonym: Notocactus uebelmannianusSN|19998]]SN|19998]] Buining, Kakt. and. Sukk. 19(9): 175-176 (1968), non Parodia uebelrnannlana Ritter, Kakt. Siidamer. 2: 425-426 (1980). On transfer to Parodia since a Parodia uebelmannianaSN|11821]]SN|11821]] already existed the name of uebelmannianus was changed to Parodia werneri, hence the name Parodia werneri is the current accepted Scientific name but many growers and plant sellers still use the old name Notocactus uebelmannianusSN|19998]]SN|19998]], so you may come across it under both names.
Stem: Shiny dark green, globular or short/squatty up to 12 cm tall and 17 cm in diameter.
Ribs: 12-16, flat, round, more ore less chinlike.
Areoles: Round, large, dull white or creamy white-felted, each with a shallow groove below.
Central spines: Usually absent.
Radial spines: About 6 spider-like, 10 to 30 mm long, appressed against the stem body, one pointing downward, unequal, white to greyish.
Flower: Small about 5 cm in diameter, short funnel-form, shiny, wine red to deep magenta of various tones, or pure yellow (Parodia werneriSN|19997]]SN|19997]] f. flaviflora). Both purple and yellow flower colours can exist side by side in some populations and the yellow being the most abundant. Therefore the more commercial but less representative purple flowered form was made the species and the more typical yellow flowered the variety.
Blooming season: Spring to early summer, once it reaches about 7 cm in diameter if kept well it will flower every year.', 'https://www.llifle.com/photos/Parodia_werneri_11608_l.jpg', 'Parodia werneri', '2025-03-21', 0x43A8D74F45954B0FA3683E372CE29927),
        (0x28AE48ECF0A845CF8D81E7251D601969, true, 'Outside they need a bright exposure, full sun or half shade in summer if the location is exceedingly hot or bright, inside needs bright light, and some direct sun. Light frost protection required for safe cultivation, but can tolerate sporadic light frost. This plants need a period of cool rest in winter to produce flowers abundantly.
', 'They are summer-growing and pretty easy plants thought slow to start. They are suited for any rich, well drained soil such us clay, pumice, lava grit, and only a little peat or leaf-mould. If potted, repot them preferably in the spring, if their roots become cramped. Generally, they should be repotted every other year in order to provide fresh soil. However, this doesn''t necessarily mean they''ll need larger containers. Fill about a quarter of the pot with broken crocks, gravel, etc. to promote good drainage. After repotting, do not water for a week or more. Water regularly during the aestival growth cycle (this plant need plenty of water, but do not overwater and let their soil dry out between waterings), and also needs to be avoided wetting the body of this plant while it is in sunlight. A wet cactus in the sun light can cause sun burning which can lead to scars or even fungal infections and death, keep rather dry in winter. No water should ever be allowed to stand around the roots.', 'Origin and Habitat: Ferocactus alamosanusSN|1694]]SN|1694]] ( comprising subsp. reppenhagenii) is known only on the western edge of the Sierra Madre Occidental in the Álamos area in southeastern Sonora and adjacent Chihuahua (atates of Chihuahua, Sinaloa and Sonora, Mexico).
Altitude: 450-1300 metres above sea level.
Habitat and Ecology: The species occurs in upper tropical deciduous forests up to pine-oak forests. Known only from a restricted area this species is not very common and is said to be heading for endangered species list. It has a small number of populations (less than 10 locations). The habitat of Ferocactus alamosanusSN|1694]]SN|1694]] is home to succulent flora and is particularly rich in local endemics such as: Echinocereus subinermisSN|21769]]SN|16544]], Echinocereus stoloniferusSN|16544]]SN|21769]] and Marshallocereus thurberiSN|8268]]SN|8268]].', 'https://www.llifle.com/photos/Ferocactus_alamosanus_13349_l.jpg', 'Ferocactus alamosanus', '2025-03-21', 0x220FEEE0BD5A438EB1B282BFFFD92315),
        (0x2E8E8526A70642F288B4A889A1D4BA54, true, 'Very cold resistant above -12° C or less for short periods of time. In the summer they need an airy location in bright sun; In mild climate they grow well when planted freely outside in well-drained soil.', 'In culture Echinocereus adustusSN|7129]]SN|7129]] is without problems, easy to grow, very attractive and regularly shows its beautiful flowers, if provided with an adequate winter rest period.', 'Usually solitary.
Stem: Green, short, cylindrical, up to 20 cm tall 4(12) cm in diameter.
Ribs: 11 to16, 5-12 mm long
Root: Fibrous.
Areoles: Ellipsoidal, length 3–4mm, width 2 mm, close set, distance 4-7 mm, at first woolly, then naked.
Radial spines: 5-18, pectinated 16-23 mm long. Cream with darker tips add-pressed.
Central spines: 0 - 1, up to 35 mm long, brown-black, stiff and straight.
Flowers: Magenta-pink, throat a lighter shade, 45-60 mm long, 40-55 mm wide. Tube length 20-40 mm, filament 15-25 mm long, stylus 25-40 mm, yellow, stigma lobes 5-6 yellowish-green.
Fruit: Ovoidal, brownish-green, length 15, diameter 10. They dry and break at maturity and ripe in 2 months.
Seed: 1-1,5 mm black.', 'https://www.llifle.com/photos/Echinocereus_adustus_14412_l.jpg', 'Echinocereus adustus', '2025-03-21', 0xF5BFA272F06B47A6AF85073E338C3A06),
        (0x33AEFFDC5FF8469597CF37F715B2D532, true, 'Keep dry at 10°C in winter, but can tolerate sporadic light frost.', 'Slow growing to start but does well under cultivation. Use very draining soil, water during the aestival growth cycle (this plant need plenty of water) But needs to be avoided wetting the bodies of these plants while they are in sunlight. A wet cactus in the sun light can cause sun burning which can lead to scars or even fungal infections and death. Needs full sun. ', 'Ferocactus schwarziiSN|14457]]SN|14457]] is a solitary slow growing barrel cactus that becomes nearly spineless when old making it a handsome plant. At a first glance the mature specimens looks more like a Echinocactus than a Ferocactus.', 'https://www.llifle.com/photos/Ferocactus_schwarzii_23546_l.jpg', 'Ferocactus schwarzii', '2025-03-21', 0x220FEEE0BD5A438EB1B282BFFFD92315),
        (0x44502C37678B4CDB980CA31A31BD56ED, true, 'They need a minimum temperature of 5-10° C (but occasionally temperatures of a few degrees below 0° are not dangerous if kept on the dry side prior to, and during, cold weather). It tends to rot in winter during the resting phase, if kept wet. In the rest period no high atmospheric humidity!!', 'Frailea castaneaSN|3524]]SN|3524]] is a summer grower species relatively easy to grow. It is sometime seen as a grafted plant but grows very well on its own roots too. Characteristically, during the dry season plants retract completely under the ground both in the wild and in cultivation too.', 'Frailea castaneaSN|3523]]SN|3524]] (a.k.a. Frailea asterioidesSN|3524]]SN|3523]]) is a very singular miniature plant, and one the of most fascinating cacti with a disk like, flattened to globose body.
Stem: It is diminutive in size and several remain solitary, never outgrowing 4-5 cm diameter. Stems are chocolate brown or dark reddish-green with 8-15 flat ribs.
Spines: 3-15 minute, short, black spider-like, appressed on the plant body and usually all bent downward.
Flower: Sulphur yellow, sometimes larger than the plant itself (4cm diameter). But don''t be disappointed when the easily produced buds fail to open. Fraileas are cleistogamous meaning that their flowers produce seed without even opening. Without the need for pollination, hence the buds rarely reach full bloom and remain closed. They will open only in great heat in the hottest, brightest, afternoon sun, if at all.
Fruits: Dry indehiscent that detach easily, pericarp membranous, fragile that break easily releasing the seed.
Seeds: Very big 3-3,5 mm wide. The seed is shaped strangely for a cactus, and is often described as “hat” or “boat” shaped with a prominent edge. That is a good description, for it is among the few cactus seeds that float! They are thought to be dispersed in habitat by floating away on runoff.', 'https://www.llifle.com/photos/Frailea_castanea_1914_l.jpg', 'Frailea castanea', '2025-03-21', 0x905050A371194C17B4DBCEE7283C5BF7),
        (0x4E3EDD2C431D46488546F94440D510AD, true, 'Reputedly Very cold resistant to frost if kept on the dry side prior to, and during, cold weather (hardy to -10 C ° C, or less for short periods).', 'Very cold resistant is a summer grower species easy to cultivate, more cold tolerant than most and less fussy regarding soil conditions.
Growth rate: It is a relatively rapidly growing and easily flowering species that will make clumps given the best conditions.
Soils: It likes very porous standard cactus mix soil, but can become too elongated if compost is too rich.
Repotting: Use pot with good drainage.
Watering: Water regularly from Spring to Autumn, but do not overwater(Rot prone), keep dry in winter.
Fertilization: Feed with a high potassium fertilizer in summer.', 'Echinocereus dasyacanthusSN|8509]]SN|5533]] is a low growing cactusunbranched or branching from the base, forming loose clumps of fewer than 20 stiff branches in old age, with its stem completely obscured by a layer of spines that can vary in colour depending on growing conditions. On some individuals, each year''s new spines make a distinct band around the plant. The result is a stem with alternating bands of colour, vaguely suggesting a rainbow and similar to, but not as bold as, the Arizona Rainbow Cactus (Echinocereus rigidissimusSN|5533]]SN|8509]]). It is quite variable.
Stems: Ovoid, becoming cylindrical with age, 10-20 (40) cm tall × 4-7 (10) cm in diameter.
Ribs: Straight, approx 15-20, crests rather sharply undulate.
Areoles: 3-5 (11) mm apart.
Spines: The stem is completely covered with short spines presenting a relatively bristly appearance. They are pink to pale yellow, white, or tan, less often dark brown or purplish. Annual growth increments are marked (often vaguely) by rings of spines with contrasting colours (depending on growing conditions) that grey with age.
Central spine: 3 to 10 central spines, up to 15 mm long, straight, spreading in all directions.
Radial spines: Appressed, 16 to 24, up to 10 mm long.
Flowers: 7-10 cm wide × 7-12 cm long; inner tepals, either yellow or rarely orange-yellow, salmon -pink to magenta with age, basal portion green in either case, tips relatively thin and delicate; The outer petals often have a darker or reddish midstripe. Anthers are yellow. The stigma has 16-20 lobes.
Flowering time: April-May.
Fruits: Dark, dull, purplish to maroon (sometimes remaining green), 2-3.5 cm, pulp white to purplish pink. The spiny fruits are edible, although acid.', 'https://www.llifle.com/photos/Echinocereus_cinerascens_14362_l.jpg', 'Echinocereus dasyacanthus', '2025-03-21', 0xF5BFA272F06B47A6AF85073E338C3A06),
        (0x579A6C3641B648BAAD785A56AC910571, true, 'They need a minimum temperature of 5-10° C (but occasionally temperatures of a few degrees below 0° are not dangerous if kept on the dry side prior to, and during, cold weather). It tends to rot in winter during the resting phase, if kept wet. In the rest period no high atmospheric humidity!!
Sun Exposure: Light shade to full sun, its colour tends to richer and darker when grown in light shade. In a shaded position the plants grow faster, but are not flat shaped and dark coloured.
', 'Frailea cataphractaSN|3597]]SN|3597]] is a summer grower species relatively easy to grow. It is sometime seen as a grafted plant but grows very well on its own roots too. Characteristically, during the dry season plants retract completely under the ground both in the wild and in cultivation too.
Growth rate: Fraileas are relatively short-lived plants, only lasting few years (rarely more than 10-15 years in cultivation) and, possible annuals in habitat! In fact they reseed readily around the base of the mother plant from self-set seed if kept reasonably moist during warm weather. It is a
good idea to keep restarting them from seed; what looks like a healthy big plant may suddenly die of old age without warning.
Soil: Use mineral well permeable substratum with little organic matter (peat, humus), plants may become too elongated if compost is too rich.
Repotting: Re-pot every 2 years. Use pot with good drainage.
Fertilization: It grows much faster with a low nitrogen content fertilizer in spring and summer. Potassium helps maintaining the plants compact and healthy.
Watering: Requires careful watering to keep plant compact. Water sparingly from March till October, the thin, fibrous roots suffer if there is humidity, therefore the plant should be watered only when the surrounding terrain is dry. Keep dry as soon as the temperature starts dropping in October and keep it perfectly dry in winter at temperatures from 5 to 15 degrees centigrade.', 'Frailea cataphractaSN|21482]]SN|3597]] is a very small depressed cactus that do usually not sprout in nature, but in culture with age begins to clump around the base and grow oddly. It is undoubtedly one of the most fascinating cacti.
Stem: Dull-green and dark-brown or purplish, globose-flattened 1-2(-4) cm in diameter, deeply imbilicate at apex
Ribs: 10 to 15 with low and broad crescent-shaped tubercles flatted above, with a purple-brown lunate, blots situated below the areoles.
Radial spines: 5-9 straight 1-2 mm long, appressed, yellowish or whitish.
Central spines: Absent.
Flowers: Sulphur yellow from the top of the plant, sometimes larger than the plant itself (4cm diameter). But don''t be disappointed when the easily produced buds fail to open. Fraileas are cleistogamous meaning that their flowers produce seed without even opening. Without the need for pollination, hence the buds rarely reach full bloom and remain closed. They will open only in great heat in the hottest, brightest, afternoon sun, if at all.
Fruits: Dry indehiscent with scales and bristles that detach easily, pericarp membranous, fragile that break easily releasing the seed.
Seeds: Comparatively large, black and shining, up to 2 mm wide, with a triangular, deeply concave face.', 'https://www.llifle.com/photos/Frailea_cataphracta_6427_l.jpg', 'Frailea cataphracta', '2025-03-21', 0x905050A371194C17B4DBCEE7283C5BF7),
        (0x5B9150519A6845559D5E3486CA3ABE12, true, '', 'The secret for keeping Fraileas happy and growing is to pot them in a rich, porous soil with good drainage and aeration, to give them lots of water and let them dry out between waterings. Fraileas do like more water than most other cacti. If you over-pot them (in about 6-7 cm pots) they grow much better and healthier, as they can be quite short-lived if not given correct growing conditions. During winter they like cool and dry places (minimum temperature of 5-10° C) but even light frosts do not harms them. Characteristically, during the dry season plants retract completely under the ground, both in the wild and in cultivation too. Occasional light spray of water during the winter helps plants from shrivelling up too much. In the summer they like the pot to be filled with rainwater quickly absorbed by the plants, and one can almost see the little bodies swelling up. After a day or two, it is best to drain off any remaining water in the under-pots.', 'Fraileas are are tiny plants with comparatively big yellow flowers, often bigger than the whole plant itself and are especially suitable for those with limited growing space. They can be easily grown in a sunny windowsill or a small greenhouse.', 'https://www.llifle.com/photos/Frailea_angelicana_28217_l.jpg', 'Frailea angelicana', '2025-03-21', 0x905050A371194C17B4DBCEE7283C5BF7),
        (0x5B9ED975589B4E0D8BA0289B76F0D7DF, true, 'Keep dry as soon as the temperature starts dropping in October and keep it perfectly dry in winter at temperatures from 5 to 15 degrees centigrade. They need a minimum temperature of 5-10° C (but occasionally temperatures of a few degrees below 0° are not dangerous if kept on the dry side prior to, and during, cold weather). It tends to rot in winter during the resting phase, if kept wet. In the rest period no high atmospheric humidity!!', 'This is a is a summer grower species relatively easy to grow. It is sometime seen as a grafted plant but grows very well on its own roots too.
Fraileas are relatively short-lived plants, only lasting few years (rarely more than 10-15 years in cultivation) and, possible annuals in habitat! In fact they reseed readily around the base of the mother plant from self-set seed if kept reasonably moist during warm weather. It is a good idea to keep restarting them from seed; what looks like a healthy big plant may suddenly die of old age without warning.
Use mineral, slightly acidic, well permeable substratum with little organic matter (peat, humus), plants may become too elongated if compost is too rich.
Requires careful watering to keep plant compact. Water sparingly from March till October, the thin, fibrous roots suffer if there is humidity, therefore the plant should be watered only when the surrounding terrain is dry.', 'Frailea alexandriSN|33228]]SN|33228]] is the only Paraguayan species with shortly columnar stems. The stems are solitary, but may occasionally produce a few shoots with age. The flowers open open normally only in great heat in the hottest, brightest, afternoon sun, if at all, but even unopened flowers (cleistogamous flowers), produce fruits with viable seeds without the need for pollination, hence the buds rarely reach full bloom and remain closed.', 'https://www.llifle.com/photos/Frailea_alexandri_27835_l.jpg', 'Frailea alexandri', '2025-03-21', 0x905050A371194C17B4DBCEE7283C5BF7),
        (0x63A7A3E39F894671B2723370B3CDA026, true, 'In winter keep completely dry at 10°C, but can tolerate sporadic light frost. Plant in good conditions will start to bloom when reach the diameter of only 7-8 cm.', 'Slow growing to start but does well under cultivation. Suited for any rich, well drained soil in full sun throughout the year. Water during the aestival growth cycle (this plant need plenty of water) But needs to be avoided wetting the bodies of these plants while they are in sunlight. A wet cactus in the sun light can cause sun burning which can lead to scars or even fungal infections and death.', 'Ferocactus fordiiSN|13617]]SN|12330]] is a single stemmed small barrel cactus although it does offset occasionally. It is similar but a bit smaller than Ferocactus viridescensSN|12330]]SN|13617]]. Two subspecies are recognized, the nominate form and subsp. borealis N.P.Taylor.
Stem: Flattened globular slowly becoming shortly elongated, 40 cm tall, 30 cm in diameter (but usually less than 20 cm in diameter and slightly more tall), depressed in the centre. Epidermis grey-green.', 'https://www.llifle.com/photos/Ferocactus_fordii_18149_l.jpg', 'Ferocactus fordii', '2025-03-21', 0x220FEEE0BD5A438EB1B282BFFFD92315),
        (0x6ABB18AC926941EA80E683D398805E00, true, 'Keep dry at 10°C in winter, but it can tolerate sporadic light frost.', 'Use very draining soil, water during the aestival growth cycle (this plant need plenty of water) But it''s necessary to avoid wetting the bodies of these plants while they are in sunlight. A wet cactus in the sun light can cause sun burning which can lead to scars or even fungal infections and death. Needs full sun.', 'Origin and Habitat: Mexico (Baja California: Only occurs naturally on the island of Cedros, off the west coast of northern Baja California and possibly on a neighboring island, West San Benitos, with some reports of it on the adjacent peninsula.)
Habitat: with a balanced and relatively high average temperature, low rainfall but relatively high humidity and specific soil composition (these conditions are difficult to imitate in cultivation, and make this species relatively problematic to grow. Ferocactus chrysacanthusSN|12323]]SN|12323]] is a small sized solitary or rarely cespitose barrel cactus with up to 6 heads. The plant is very densely spined (one of the spiniest of the Ferocacti) and because of that, will tolerate full sun.', 'https://www.llifle.com/photos/Ferocactus_chrysacanthus_3310_l.jpg', 'Ferocactus chrysacanthus', '2025-03-21', 0x220FEEE0BD5A438EB1B282BFFFD92315),
        (0x7B73A6E1167041EE9E2912401F1F5A49, true, 'Tender. This cactus cannot tolerate any frost and can be difficult to get it to look its best without a good amount of heat. It can be grown outdoors in frost-free climates.', 'Parodia magnificaSN|20453]]SN|20453]] is an easy to grow ornamental species suited for any well drained soil in half or full sun.
Growth rate: It is a relatively rapidly growing and easily flowering species that will make clumps given the best conditions.
Soil and pots: It likes deep pot with generous drain holes, needs a very airy potting medium very permeable to water which mainly consists of non organic material such us clay, pumice, lava grit, expanded slate and only a little peat or leaf-mould, slightly acid, pH-value between 4,5–6. Re-pot every two years.
Fertilization: Need a perfect fertilizer diet in summer. Use preferably a cacti and succulents fertilizer with high potassium content including all micro nutrients and trace elements or slow release fertilizer.
Exposure: This plant need full sun but tolerate moderate shade, and a plant that has been growing in shade should be slowly hardened off before placing it in full sun as the plant will be severely scorched if moved too suddenly from shade into sun.
Watering: No water should ever be allowed to stand around the roots. Keep almost completely dry in winter. However this spurge will tolerate dryness and can even thrives in poor, dry soils, but do better when grown in nutrient-rich soils with regular watering.', 'Parodia magnificaSN|11865]]SN|20453]], still known in cultivation with its old name Eriocactus magnificusSN|11866]]SN|20454]], is a bluish-green geometric globular cactus with wool that grows in clusters and produce absolutely brilliant yellow flowers. These cacti develop a slight depression on the crown, which may become distorted with age. Parodia magnificaSN|20453]]SN|20453]] glistens under a haze of pale yellow spines. Cristate (wavy edged) forms are avalible but these are usually grafted plants.
Similar species: It resembles very well to the Parodia warasiiSN|20453]]SN|11865]] (= Eriocactus warasiiSN|20454]]SN|11866]]).
Habit: Plants at first solitary, forming large clustering mounds in time.
Stems: Globose, becoming short cylindrical with age, blue- green, glaucous, oblique apically. It grows 30 (or more) cm high and 7-15 cm in diameter.
Ribs: 11-15, straight, symmetrical, acute.
Areoles: White at first, later yellowish close together or almost contiguous.
Spines: 12-15 or more, bristle-like, thin, flexible, goldens yellow, 8-20 mm long.
Flowers: Borne several at a time apically, funnel-shaped, sulphur yellow, 4,5-5,5 cm long and in diameter; pericarpels with dense white wool and brownish bristles.
Blooming season: Flowering occurs in summer through early fall and will bloom several times during warm weather.
Fruits: Globose, pink, to 1 cm in diameter.
Seeds: Obovoid to club shaped, reddish brown, spiny tuberculate.', 'https://www.llifle.com/photos/Parodia_magnifica_27803_l.jpg', 'Parodia magnifica', '2025-03-21', 0x43A8D74F45954B0FA3683E372CE29927),
        (0x8FF9694FBE2747BB83D6F02EB5ECA4FB, true, 'In winter keep completely dry at 10°C. This usually aids in maintaining a healthier plant, but it can tolerate sporadic light frost.', 'Plants are slow growing to start, but are easy to grow and require little care once they have reached a nice flowering size. F. glaucescens is suited for any rich, well drained soil in full sun, through-out the year. Pot culture: It grows best in a fairly roomy, well-drained container filled with a porous cactus soil mixture that doesn''t contain too much humus. To insure robust plants, water and fertilize during the aestival growth cycle. This plant needs plenty of water (indicatively, about once a week). But it''s necessary to avoid wetting the bodies of these plants while they are in sunlight. A wet cactus in the sun light can cause sun burning which can lead to scars, or even fungal infections and death.', 'Ferocactus glaucescensSN|1690]]SN|1532]] is a medium sized solitary or basally suckering, barrel cactus. Multiple heads are produced as the plant ages and can form a very large mound. This species is sometimes confused with Ferocactus echidneSN|1532]]SN|1690]] (DC.) Britton & Rose and may even hybridize with that species.
Stems: Glaucous grey, up to 55 cm in height, 50 cm in diameter. Globular depressed at the apex, it becomes shortly columnar as it ages.', 'https://www.llifle.com/photos/Ferocactus_glaucescens_19679_l.jpg', 'Ferocactus glaucescens', '2025-03-21', 0x220FEEE0BD5A438EB1B282BFFFD92315),
        (0xBF2B9648CCE54BC1A2DF3013996DE8A3, true, '', 'In cultivation the strawberry hedgehog grows rather slowly and it is sensitive to overwatering (rot prone) needs a very good drainage to avoid rotting, but requires more moisture than true desert cacti to grow and produce flowers, Keep drier and cool in winter. Need full sun. It is cold resistant to -10° ( or less depending on clones) for short periods of time. It is a fine plant for a rock garden or container, contrasts well with agaves, yuccas, and low-growing flowering plants. It will show its flowers only if we provide an adequate winter rest period.', 'Echinocereus engelmanni var armatus is the most formidably spiny extreme of the species.
Habit: It is a clumping columnar cactus, 6-25-branched, ultimately forming somewhat open clumps of stems.
Stems: Suberect or erect light green, cylindrical or somewhat tapering distally, usually 15-20 cm tall, and about 5 cm in diameter, branching freely from the base;
Ribs: 11 to 14 low obtuse, tubercles indistinct, crests slightly undulate.
Areoles: 6-15 mm apart, wool present in first year only.
Spines: 8-20 per areole up to 13 cm long; divergent-porrect, stout, and rigid, straight or curving and somewhat twisted, brownish-pink or (usually) dull golden-yellow.
Radial spines: Lighter whitish to creamy coloured 8-20 mm long long, spreading.
Flowers: From purple to lavender. The flowers are up to 7 cm in diameter, 5-8 cm long . Flower tube hairy.
Blooming season: Spring, flowers are diurnal close at night and reopen in the morning and last for about five days.
Fruit: Red or orangish 2,5-4cm long, spherical, fleshy, pulp whitish be-coming infused with pink or red from the skin. The fruit is edible, it is said to taste like strawberry.', 'https://www.llifle.com/photos/Echinocereus_engelmannii_var._armatus_14311_l.jpg', 'Echinocereus engelmannii var. armatus', '2025-03-21', 0xF5BFA272F06B47A6AF85073E338C3A06),
        (0xC2E13B7E7D4D4DFC83BB4F6E8AB7CE39, true, 'It is reputedly resistant to frost if kept on the dry side prior to, and during, cold weather and requires a winter rest period (hardy to -5° C, or less for short periods). It grows in nature at high altitudes, and does not thrive well at high temperatures in cultivation. It will often go dormant in mid-summer, and resume growth again when the weather cools in late August. It is generally accepted that plants kept at too high a temperature, or watered too much during the winter rest period, will not bloom the following year.
Exposition: The plant tolerates extremely bright situations but enjoys filtered sunlight or afternoon shade, inside it needs bright light, and some direct sun. Tends to stay compact in strong light, which encourages flowering and heavy spine production, but is likely to suffer from sun scorch or stunted growth if over exposed to direct sunlight during the hottest part of the day in summer.', 'Parodia lauiSN|5783]]SN|5783]] (hausteiniana) comes from mountainous areas, and in its natural habitat, warm rain falls and waters the plants, and in the winter, the it endures long, dry, and temperate zone conditions. It would be wise and fun to duplicate the plant''s natural growing conditions and watch it mature into a healthy potplant. It has delightful flowers and the plant remains compact. It is easy to cultivate and recommended for beginners. Warning the central spines end with a hook and on occasion cling to curtains or clothing. If you accidentally pull the plant out of the pot, you should put it back in its place and not watered for 2 weeks.
Growth rate: It is a slow growing but easily flowering species. This species start blooming when only 2.5 cm in height.
Soils: This species is easy to cultivate in a very open mineral mix with at least 50% sand or pumice grit.
Repotting: It is a small container size plants and prefers deep pots and good drainage to accommodate its roots, but it is rot prone, because of the sensitivity to excess of watering. It will occupy a small pot comfortably, and eventually remains a manageable sized house plant. It is better that it is repotted regularly. Repotting will increase the number of flowers produced. Re-pot yearly until it reaches about 5 cm in size, then every two or three years will suffice. Repotting is best done at the end of winter, but can be done at other times, too. Do not water for a couple of weeks after re-potting, to reduce risk of root rot via broken roots. A layer of ''pea'' gravel at the bottom of the pot improves drainage. A layer of decorative gravel as a top dressing helps prevent the caking of the potting mix, which decreases the rate of water absorption. It also keeps the perlite and pumice from blowing everywhere, and looks nice.', 'Parodia lauiSN|5781]]SN|5783]] is a small growing, solitary cactus to only 5 cm in diameter with remarkable thick, yellow or amber-coloured spines. It is a orange-red flowered form of Parodia hausteinianaSN|5783]]SN|5781]], which itself has blooms ranging from yellow to orange.
P. laui and P. hausteiniana are almost identical, came from the same small area, and it is really difficult to tell the two apart when not in flower so most authors choose to lump them together.
Stem: Unbranched, light green, globose to short cylindrical, to 5 cm in diameter.
Ribs: About 13, slightly twisted.
Areoles: Round to elliptical with white wool.
Central spines: 4, forming a cross, stout, yellow, hooked, to 13 mm long.
Radial spines: 26-30, thin, radiating, flattened against the stem surface, yellow, becoming whitish with age, to 8(-10) mm long.
Flowers: Orange to orangew-red, to 10 mm long and in diameter; pericarpels and floral tubes with scales and bristles.
Fruits: Egg-shaped, olive green, 3-4 mm long.
Seeds: Dark brown, finely tuberculate.', 'https://www.llifle.com/photos/Parodia_laui_22316_l.jpg', 'Parodia laui', '2025-03-21', 0x43A8D74F45954B0FA3683E372CE29927),
        (0xCDB51915D454487B97043D6D16F5944C, true, 'They need a minimum temperature of 5-10° C (but occasionally temperatures of a few degrees below 0° are not dangerous if kept on the dry side prior to, and during, cold weather). It tends to rot in winter during the resting phase, if kept wet. In the rest period no high atmospheric humidity!!
Sun Exposure: Light shade to full sun, its colour tends to richer and darker when grown in light shade. In a shaded position the plants grow faster, but are not flat shaped and dark coloured.', ' Frailea pumilaSN|2188]]SN|2188]] f. rubrispina is a summer grower species relatively easy to grow. It is sometime seen as a grafted plant but grows very well on its own roots too. Characteristically, during the dry season plants retract completely under the ground both in the wild and in cultivation too.
Growth rate: Fraileas are relatively short-lived plants, only lasting few years (rarely more than 10-15 years in cultivation) and, possible annuals in habitat! In fact they reseed readily around the base of the mother plant from self-set seed if kept reasonably moist during warm weather. It is a
good idea to keep restarting them from seed; what looks like a healthy big plant may suddenly die of old age without warning.
Soil: Use mineral well permeable substratum with little organic matter (peat, humus), plants may become too elongated if compost is too rich.
Repotting: Re-pot every 2 years. Use pot with good drainage.
Fertilization: It grows much faster with a low nitrogen content fertilizer in spring and summer. Potassium helps maintaining the plants compact and healthy.
Watering: Requires careful watering to keep plant compact. Water sparingly from March till October, the thin, fibrous roots suffer if there is humidity, therefore the plant should be watered only when the surrounding terrain is dry. Keep dry as soon as the temperature starts dropping in October and keep it perfectly dry in winter at temperatures from 5 to 15 degrees centigrade.', 'Frailea pumilaSN|3597]]SN|2188]] f. rubrispina is a morphological form of Frailea pumilaSN|2188]]SN|2188]] distinguished from the latter by the red coloured young spines. The differences with other Frailea pumilaSN|2188]]SN|2188]] are in reality very minimal and the two plants are not readily distinguishable, if not for the colour of the new spines.
Habit: Plant cespitose, sprouting around the base to form clumps.
Roots: It has a well-developed contractile tuberous root system. These tuberose roots have the function of storing enough sustenance so that plants can survive the periods of drought that they have to endure. Tuberous roots also have the function of anchoring the plants into the ground.
Stem: Sub-globular, flattened and umbilicate at apex, 2-5 cm in diameter and 2 cm high, deep green, sometimes becoming reddish.
Ribs: 13 to 20, flat, more distinct than in the related species, more or less tuberculate.
Areoles: Small, nearly circular.
Spines: All pubescent, 1-5 mm long, brownish (red on new growing apex) not readily distinguishable as centrals and radials
Radial spines: 9 to 14, setaceous, more or less appressed.
Central spines: 1-2(-3), erect.
Flower: 2 cm long, yellow; axils of scales on the ovary and flower-tube woolly and setose.
Fruits: Green.
Seeds: Smooth, brown, obovate, 1,5 mm long, angled on the back; depressed hilum much smaller than in Frailea cataphractaSN|2188]]SN|3597]].', 'https://www.llifle.com/photos/Frailea_pumila_f._rubrispina_15668_l.jpg', 'Frailea pumila f. rubrispina', '2025-03-21', 0x905050A371194C17B4DBCEE7283C5BF7),
        (0xF35062BE3E3A4C38BF8449D34726D20A, true, 'It likes warmth (recommended minimum winter temperature 5° C) however plants kept perfectly dry can can survive low temperatures, approx. -5°, but for safe cultivation it is best to avoid freezing temperatures.', 'Parodia andreaeSN|5835]]SN|5835]] is relatively easy to grow on its own roots.
Soil: Grow it in an open sandy-gritty cactus compost.
Pots: It needs a relatively shallow pot to accommodate its fibrous roots and provide a very good drainage. It may stay in the same pot for many years.
Watering: Water in moderation, it prefer a completely dry place during winter. Mature individuals easily rot and die especially after planting so be extremely cautious with watering. Keep dry in winter or when night temperatures remain below 10° C. Water it less than average if in bigger pots.
Special need: Provide very good ventilation. Nearly all problems occur as a result of overwatering and poor ventilation, especially when weather conditions are dull and cool or very humid.
Fertilization: Feed them once during the growing season with a fertilizer specifically formulated for cactus and succulents (high potash fertilizer with a dilute low nitrogen), including all micro nutrients and trace elements diluted to ½ the strength recommended on the label. They thrive in poor soils and need a limited supplies of fertilizer to avoid the plants developing excess vegetation, which is easily attacked by fungal diseases.
Exposure: It will do its best with lots of sun and become stressed with inadequate light which could result in poor growth and unnatural shape.', 'Parodia andreaeSN|5820]]SN|5835]] is a local or morphological form of the wide ranging and variable Parodia proceraSN|5820]]SN|5820]] distinguished by light red-brown spines, large white-felted areoles and showy golden-orange flowers around the very woolly stem apex in mid summer. The differences with other Parodia proceraSN|5820]]SN|5820]] are in reality very minimal and most botanist agree on the fact that both should all be included in the Parodia proceraSN|5835]]SN|5820]], and the two plants are not readily distinguishable, if not for the geographical provenance.
Habit: This species is usually solitary, sometimes forming clumps.
Stems: Globose to elongate, 10-12 cm in diameter, with white woolly tips.
Ribs: Approx 13 more or less vertical, well defined, 5-8 mm hight and tuberculate.
Areoles: Large, white-felted and densely set.
Central spines: Up to 7, brownish or light red-brown, mostly straight, subulate, 2-2,5 cm long.
Radial spines: About up to 20, dull white to yellow-brown, thin, straight, 1-1,5 cm long.
Flowers : Golden orange, 3 cm long and 4-5 cm in diameter; pericarpels and floral tubes with white hairs below, brown hairs and bristles above.
Blooming season: Flowering occurs in summer through early fall and will bloom several times during warm weather.
Fruits: Almost spherical, brownish, small, up to 4 mm in diameter.
Seeds: Small, brownish, shiny.', 'https://www.llifle.com/photos/Parodia_andreae_18658_l.jpg', 'Parodia andreae', '2025-03-21', 0x43A8D74F45954B0FA3683E372CE29927),
        (0xF835184A8DD5491C8E1D79C8D853C9C6, true, '', 'Echinocereus reichenbachiiSN|7575]]SN|7575]] is sensitive to overwatering (rot prone) needs a very good drainage to avoid rotting, but requires more moisture than true desert cacti to grow and produce flowers, Keep drier and cool in winter. Need full sun. It is very cold resistant from -10° to -25° C (depending on clones) or less for short periods of time. It is a fine plant for a rock garden or container, contrasts well with agaves, yuccas, and low-growing flowering plants.', 'Echinocereus reichenbachiiSN|7575]]SN|7575]] is a slowly branching cylindrical shaped cactus more or less cespitose with up to 12 branches covered strongly pectinate, appressed truly lacy spines. The flowers are very showy, fragrant, produced in profusion, rather variable as to size, often 6 to 7 cm long and fully as broad, opening during the day, always closing at night and sometimes opening the second day, purple. The basis of flowers are clothed with dense greyish wool. It is a distinct species with six subspecies: the nominate form, subsp. armatus (Poselg.) N.P.Taylor, subsp. baileyi (Rose) N.P.Taylor, subsp. burrensis G.Frank, Metorn & E.Scherer, subsp. fitchii (Britton & Rose) N.P.Taylor and subsp. perbellus (Britton & Rose) N.P.Taylor.
Stem: Erect, simple or commonly branched to form cluster of up to 12 upright stems, globose when very young, elongate or short cylindrical when mature, (2.5)7-20(-40) cm tall, (2,5-) 5-9(-10) cm in diameter dark green.
Ribs: 10-19 narrow, definite, straight or slightly undulate divided into distinct tubercles.
Areoles: Elliptic elongated vertically, approximate, 1.5-3 mm long, 1-6(-10) mm apart, quite woolly when young, and bare when older
Radial spines: 20 to 36, rigid, slender, straight, spreading to slightly curved, held closely against the the ribs of the stems, organized in 2 series, pectinately arranged or nearly so, 5 to 8 mm long. Top ones very tiny, almost bristlelike; laterals more robust; lower 1-3 somewhat smaller; spines of adjacent clusters often interlocking.
Flowers: Beautiful, very large, abundant, diurnal, scented, intense pink to purple, 5 to 12 cm long and fully as broad. Flower tube 22-40 × 10-30 mm covered with white, cobwebby wool, 5-15 mm long, and clusters of 10-14 very fine, hairlike, white, grey, or black spines c 6 mm long.
Blooming season: Early May to Late June.', 'https://www.llifle.com/photos/Echinocereus_reichenbachii_2731_l.jpg', 'Echinocereus reichenbachii', '2025-03-21', 0xF5BFA272F06B47A6AF85073E338C3A06),
        (0xFE7A2D715F664A51AA6DC96B4205DA6D, true, 'When dormant, the plant is slightly cold tolerant (down to nearly -2° C or less), but when left out it is more sensitive to frost. However warmth throughout the year will increase the grower''s success (at minimum temperatures above 5 degrees centigrade during rest season). During the summer it is best to keep the plants outside where the temperature can rise to over 30 C with no harm to the plant. This plants need a period of cool rest in winter to produce flowers abundantly.', 'Ferocactus gracilisSN|11980]]SN|11980]] is a summer-growing and pretty easy plant thought slow to start. It makes great potted specimens, and is a great cactus for beginning collectors.', 'Ferocactus gracilisSN|10102]]SN|11980]] is an exceptionally attractive red-spined barrel with remarkably red flowers and yellow fruit, which was discovered by Mr. Howard E. Gates in 1928. Mr. Gates published the species in 1933. It is quite variable. In Baja California Ferocactus gracilisSN|11980]]SN|11980]] can be confused with Ferocactus cylindraceusSN|11980]]SN|10102]]; the latter species has yellow flowers while those of the former are almost always red.', 'https://www.llifle.com/photos/Ferocactus_gracilis_7537_l.jpg', 'Ferocactus gracilis', '2025-03-21', 0x220FEEE0BD5A438EB1B282BFFFD92315);